vich_uploader:
    db_driver: orm

    mappings:
        apple_image:
            uri_prefix: /uploads/apples
            upload_destination: '%kernel.project_dir%/public/uploads/apples'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true